apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: rabbitmq:3-management
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: default
spec:
  selector:
    app: rabbitmq
  ports:
  - port: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq-management
  namespace: default
spec:
  type: NodePort
  selector:
    app: rabbitmq
  ports:
  - port: 15672
    nodePort: 32672